# Generated by Django 4.1.4 on 2022-12-15 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yarn_toy_shop.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('telephone_number', models.CharField(max_length=12, validators=[yarn_toy_shop.core.validators.telephone_number_length_validator, yarn_toy_shop.core.validators.telephone_number_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
